version: "3"

services:
  # RDB
  preset_db_proto:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --range_optimizer_max_mem_size=16777216
    environment:
      MYSQL_DATABASE: preset_proto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - sticky_volume:/var/lib/mysql
      - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d/  # 서비스명

  # Redis
  preset_redis_proto:
    image: redis:7.0
    container_name: preset_redis7_proto
    ports:
      - 6379:6379
    volumes:
      - sticky_volume:/redis/data
      - ./config/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: on-failure
    command: redis-server /usr/local/conf/redis.conf

# Volume Container
volumes:
  sticky_volume:
